# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source "https://github.com/CocoaPods/Specs"
source "https://github.com/yumimobi/Specs"

target 'ZPLAYAdsPreviewTool' do
  pod 'PlayableAdsPreviewerDemo', :path => '../'
  pod 'TSMessages'
  pod 'PlayableAdsPreviewer' ,'2.4.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Bugly'

  target 'ZPLAYAdsPreviewTool_Tests' do
    inherit! :search_paths
  end
end

target 'ZPLAYAdsPreviewTool_beta' do
  pod 'PlayableAdsPreviewerDemo', :path => '../'
  pod 'TSMessages'
  pod 'PlayableAdsPreviewer' ,'2.4.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Bugly'
end
