use_frameworks!

target 'PlayableAdsPreviewer_Example' do
  pod 'PlayableAdsPreviewerDemo', :path => '../'
  pod 'TSMessages'
  pod 'PlayableAdsPreviewer' ,'0.6.0'

  target 'PlayableAdsPreviewer_Tests' do
    inherit! :search_paths

    
  end
end
