# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new Beta Build to HockeyApp"
  lane :beta do
  next if ENV["TRAVIS_PULL_REQUEST"] != "false" or ENV["TRAVIS_BRANCH"] != "beta"
  cocoapods(podfile: "Example", repo_update: true)
    
  keychain_name = "PlayableAdsPreviewer-iOS-certs"
  keychain_password = SecureRandom.base64

  create_keychain(
    name: keychain_name,
    default_keychain: true,
    unlock: true,
    password: keychain_password,
    timeout: 3600
  )

  import_certificate(
    log_output: true,
    certificate_path: "fastlane/Certificates/ZplayAds_Distribute.p12",
    certificate_password: ENV["KEY_PASSWORD"],
    keychain_name: keychain_name,
    keychain_password: keychain_password
  )

  # Build
  gym(
    scheme: "ZPLAYAdsPreviewTool_beta",
    workspace: "Example/ZPLAYAdsPreviewTool.xcworkspace",
    configuration: "Release",
    clean: true,
    include_symbols: true,
    export_method: "enterprise"
  )

  # Push to HockeyApp
  hockey(
    api_token: "b23874100f5346cdb613ca63c57393eb",
    public_identifier: 'd2edc6e9420244a38e3702437a168c55',
    notify: "1",
    status: "2",
    commit_sha: ENV["TRAVIS_COMMIT"],
    notes: ENV["TRAVIS_COMMIT_MESSAGE"],
  )

  delete_keychain(
    name: keychain_name
  )
  end
end
